import { useEffect, useState } from 'react'
import clsx from 'clsx'
import dayjs from 'dayjs'
import Head from 'next/head'

import { getAvailableSlots, bookSlot } from '../globals'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [auth, setAuth] = useState()
  const [data, setData] = useState()
  const [table, setTable] = useState(0)
  // const [date, setDate] = useState(dayjs())
  const [slots, setSlots] = useState([])
  const [booked, setBook] = useState(false)

  function bookTable() {
    bookSlot({tableNumber: table, slots: [...slots], date: dayjs().format('YYYY-MM-DD')}, auth.token).then(res => {
      if (res.status === 201) {
        setBook(true)
      }
    })
  }

  function _setSlot(_slot) {
    let __slot = slots.find(i => i === _slot.slotNumber)
    if (!__slot) {
      setSlots([...slots, _slot.slotNumber])
    }
  }

  useEffect(() => {
    let auth = localStorage.getItem('auth')
    if (auth) {
      auth = JSON.parse(auth)
      setAuth(auth)
    }
  }, [])

  useEffect(() => {
    if (auth && table) {
      getAvailableSlots(table, dayjs().subtract(1, 'day').format('YYYY-MM-DD'), auth.token).then(res => {
        if (res.status === 200) {
          setData(res.slots)
        }
      })
    }
  }, [table])

  return (
    <div className={styles.container}>
      <Head>
        <title>Table Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-7xl mx-auto">
        <div className="flex items-center border-b border-slate-500 py-6 md:justify-start md:space-x-10">
          <p className="text-xs text-gray-200 hover:text-gray-500">BOOKINGS</p>
          <p className="text-xs text-gray-200 hover:text-gray-500">CALENDAR</p>
          <p className="text-xs text-gray-200 hover:text-gray-500">SEATING</p>
          <p className="text-xs text-gray-200 hover:text-gray-500">REPORTING</p>

          <div className="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
            <a href="#" className="whitespace-nowrap text-base font-medium text-white hover:text-slate-300 mx-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
              </svg>
            </a>
            <a href="#" className="whitespace-nowrap text-base font-medium text-white hover:text-slate-300 mx-4">
              EN 
            </a>
            <a href="#" className="whitespace-nowrap text-base font-medium text-white hover:text-slate-300 mx-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-app-indicator" viewBox="0 0 16 16">
                <path d="M5.5 2A3.5 3.5 0 0 0 2 5.5v5A3.5 3.5 0 0 0 5.5 14h5a3.5 3.5 0 0 0 3.5-3.5V8a.5.5 0 0 1 1 0v2.5a4.5 4.5 0 0 1-4.5 4.5h-5A4.5 4.5 0 0 1 1 10.5v-5A4.5 4.5 0 0 1 5.5 1H8a.5.5 0 0 1 0 1H5.5z"/>
                <path d="M16 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
              </svg> 
            </a>
            <button type="button" className="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span className="sr-only">Open user menu</span>
              <img className="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
            </button>
          </div>
        </div>
      </div>

      <aside className={clsx(styles['side-nav'], table && styles['side-nav--animatable'], table && styles['side-nav--visible'])}>
        <nav className={styles['side-nav__container']}>
          <div className='flex p-2 justify-around'>
            <div className='mt-3'>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-arrow-left-short" viewBox="0 0 16 16">
                <path fillRule="evenodd" d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
              </svg>
            </div>
            <div>
              <p className='text-center'>TODAY</p>
              <p className='text-xs'>{dayjs().format('DD.MM.YYYY')}</p>
            </div>
            <div className='mt-3'>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-arrow-right-short" viewBox="0 0 16 16">
                <path fillRule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
              </svg>
            </div>
          </div>
          <button className={styles['side-nav__hide']} onClick={_ => setTable(0)}>close</button>
          <ul className="side-nav__content">
            {data ? data.filter(i => i.status === 'AVAILABLE').map((i, j) => (
              <li key={j} className='flex justify-around py-3 border-b border-slate-500 cursor-pointer' onClick={_ => {_setSlot(i)}}>
                <span>{i.slotNumber}</span>
                <span>-</span>
                <span>{i.slot}</span>
              </li>
            )) : (
              <li className='flex justify-around py-3 border-b border-slate-500 cursor-pointer' onClick={_ => {_setSlot(i)}}>
                <span></span>
                <span>Loading</span>
                <span></span>
              </li>
            )}
          </ul>
        </nav>
      </aside>

      {slots && slots.length > 0 && (
        <aside className={clsx(styles['side-nav1'], slots.length > 0 && styles['side-nav--animatable'], slots.length > 0 && styles['side-nav--visible'])}>
          <nav className={styles['side-nav__container1']}>
            <div className='flex p-2 justify-between'>
              <div className='mt-3 text-xs'>{dayjs().format('dd DD.MM.YY')}</div>
              <div></div>
              <div className='mt-3'>{table}</div>
            </div>
            <button className={styles['side-nav__hide']} onClick={_ => setSlots([])}>close</button>
            <div className='p-8 w-full'>
              <div className='flex'>
                Slots: &nbsp;<p className="side-nav__content">{slots && slots.join(',')}</p>
              </div>
              <input placeholder='Name' className='placeholder:text-slate-200 bg-transparent border-b border-slate-100' />

              <button className='m-2 py-4 px-8 text-white rounded-md mr-2 text-xs' style={{background:'#d0a248'}} onClick={bookTable}>{booked ? 'Booked' : 'MAKE RESERVATION'}</button>
            </div>
          </nav>
        </aside>
      )}

      <div className='w-full' style={{ height: '100vh' }}>
        <div className='w-full p-4 py-6 flex'>
          <button className='ml-auto py-4 px-8 text-white rounded-md mr-2' style={{background:'#d0a248'}}>NEW RESERVATION</button>
          <button className='py-4 px-8 text-white rounded-md' style={{background:'#595f4a'}}>WALK IN</button>
        </div>

        <div className='grid grid-cols-3'>
          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(1) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>01</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(2) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>02</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-3 w-64'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background: '#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background: '#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background: '#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background: '#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background: '#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background: '#20661f'}}></div>
            </div>

            <div className='m-3 w-72 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(3) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>03</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(4) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>04</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(5) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>05</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(6) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>06</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(6) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>07</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(7) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>08</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-3 w-64'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
            </div>

            <div className='m-3 w-72 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(8) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>09</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(9) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>10</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#906b27'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(10) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>11</h1>
            </div>
          </div>

          <div className='relative'>
            <div className='m-3 mx-9 grid grid-cols-2 w-48'>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full mb-9' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
              <div className='w-16 h-16 rounded-full' style={{background:'#20661f'}}></div>
            </div>

            <div className='m-3 w-52 h-28 shadow-md absolute top-5 rounded-lg cursor-pointer' style={{backdropFilter: 'blur(7px)', background: '#ffffff40'}} onClick={_ => { setTable(11) }}>
              <h1 className='p-2 text-white font-light text-xl text-right'>12</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
